### ISSUE TITLE
Missing Carlabs.Getit.Examples.csproj

### ISSUE THREAD

**Issue by bpopow** [Revmaker/Getit#21]
I wanted to try out the getit library, it looks really helpful. Because im pretty new to GraphQL in general, i thought i look into the source code how its done.

There seems to be an `Carlabs.Getit.Examples.csproj` missing. Is that maybe a mistake? I thought this might help me get started.

**Comment by sganz** [comment]
It might have been removed a while back as most of that testing went into Unit Tests as I recall.

**Comment by bpopow** [comment]
@sganz yes, it is pretty simple, works great so far. One thing im missing though are mutations. Is that maybe something which is planned for the future?

**Comment by sganz** [comment]
Never did anything with mutations as we only (by design) had read-only data in the service. I would expect it to not be too difficult, but would require some thinking to make sure the the parser would still work OK. Generating the code might not be too bad. 

Sandy
